# Generated by Django 4.0.4 on 2022-05-01 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author_id',
            new_name='author',
        ),
    ]
