# Generated by Django 4.0.4 on 2022-05-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='body',
            field=models.CharField(max_length=300),
        ),
    ]
