# Generated by Django 4.0.4 on 2022-05-01 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_author_id_blogpost_author'),
        ('comment', '0002_alter_postcomment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost'),
            preserve_default=False,
        ),
    ]
